### PR TITLE
Update for TB115

### PR DESCRIPTION
**Pull request by jobisoft**
This update is using a different logic, to simplify the code and make the upgrade for TB115 possible.

This add-on use the `onMessageDisplayed` event to trigger our action from the WebExtension background script. The Experiment part only sets the new policy and reloads the message. Everything else is done in the background. When a message is switched from Block to Allow, it is reloaded immediately to show the content.

I assume the difference to the current add-on version is, that we act after the message is already displayed, not before. (You can see the remote content banner for a split second). Since the default from Thunderbird is to always block content, we should never get into the situation, that we showed remote message content, which we actually did not want, before we could set the correct remote content policy. The add-on basically only relaxes the policy from `Block` to `Allow`. 

To increase security, this PR also enforces for all messages which have been set to `Allow`, that the remote content policy is set back to `Block` after some time. This can be removed if not desired.

The two needed Experiments look like they are candidates for core implementation. The LegacyPrefs API can be replaced by local storage.

### CODE REVIEW

**Comment by jikamens** [comment]
>To increase security, this PR also enforces for all messages which have been set to `Allow`, that the remote content policy is set back to `Block` after some time. This can be removed if not desired.

This seems unnecessary and counter-intuitive. Without this add-on, once remote content in a message has been allowed, Thunderbird never goes back and unallows it later, so I don't see why this add-on should behave this way. I've used this add-on literally for years and I have never wanted this behavior for a single message.

Please either remove this functionality from the PR or create a preference to enable it which is disabled by default.

**Comment by jobisoft** [comment]
Thanks for allowing the temporary behavior to be available behind a new option. Updated the PR accordingly.

I also added code to apply the policies on any already opened message, when the add-on is enabled.

**Comment by jobisoft** [comment]
Can we move this forward?

**Comment by jikamens** [comment]
I need to review the PR but it's not at the top of my to-do list yet. Working on getting stuff done so I can do this.

**Comment by jikamens** [comment]
I did a bunch of stuff in #9 and merged it. I couldn't push to your branch so I had to do a separate PR. This is ready to ship. Thanks for your help!

**Pull request merged**
